groups:
  - name: devs # name of the group
    reviewers: 3 # how many reviewers do you want to assign?
    usernames: # github usernames of the reviewers
      - hi0826
      - j03y14
      - yoonwoo123
      - msmk530
